// ============================================================
// moves-config.js — Banco de dados de golpes do Boss Raid
// Importado por battle.js e battle.html
//
// Formato de cada golpe:
//   name, type, cat (physical|special|status), power, acc, pp
//   effect, effectChance, stat, stages (para buffs/debuffs/secondary)
//   priority: número inteiro (padrão 0; Quick Attack = 1)
//   effect especiais: 'leech_seed', 'double_buff', 'quick_attack_priority'
// ============================================================

export const MOVES_DB = {
  // ── Normal ──────────────────────────────────────────────────
  tackle:       {name:'Tackle',        type:'normal',  cat:'physical', power:40,  acc:100, pp:35},
  scratch:      {name:'Scratch',       type:'normal',  cat:'physical', power:40,  acc:100, pp:35},
  pound:        {name:'Pound',         type:'normal',  cat:'physical', power:40,  acc:100, pp:35},
  quick_attack: {name:'Quick Attack',  type:'normal',  cat:'physical', power:40,  acc:100, pp:30,
                  priority:1},                          // prioridade alta — age primeiro no turno
  body_slam:    {name:'Body Slam',     type:'normal',  cat:'physical', power:85,  acc:100, pp:15},
  hyper_voice:  {name:'Hyper Voice',   type:'normal',  cat:'special',  power:90,  acc:100, pp:10},
  swift:        {name:'Swift',         type:'normal',  cat:'special',  power:60,  acc:null, pp:20},
  slash:        {name:'Slash',         type:'normal',  cat:'physical', power:70,  acc:100, pp:20},
  fury_swipes:  {name:'Fury Swipes',   type:'normal',  cat:'physical', power:18,  acc:80,  pp:15},
  rapid_spin:   {name:'Rapid Spin',    type:'normal',  cat:'physical', power:50,  acc:100, pp:40},
  skull_bash:   {name:'Skull Bash',    type:'normal',  cat:'physical', power:130, acc:100, pp:10},
  take_down:    {name:'Take Down',     type:'normal',  cat:'physical', power:90,  acc:85,  pp:20},
  retaliate:    {name:'Retaliate',     type:'normal',  cat:'physical', power:70,  acc:100, pp:5},
  assurance:    {name:'Assurance',     type:'dark',    cat:'physical', power:60,  acc:100, pp:10},
  head_smash:   {name:'Head Smash',    type:'rock',    cat:'physical', power:150, acc:80,  pp:5},
  // ── Normal status ───────────────────────────────────────────
  growl:        {name:'Growl',         type:'normal',  cat:'status',   power:null,acc:100, pp:40,
                  effect:'debuff', stat:'atk', stages:-1},
  leer:         {name:'Leer',          type:'normal',  cat:'status',   power:null,acc:100, pp:30,
                  effect:'debuff', stat:'def', stages:-1},
  tail_whip:    {name:'Tail Whip',     type:'normal',  cat:'status',   power:null,acc:100, pp:30,
                  effect:'debuff', stat:'def', stages:-1},
  screech:      {name:'Screech',       type:'normal',  cat:'status',   power:null,acc:85,  pp:40,
                  effect:'debuff', stat:'def', stages:-2},
  scary_face:   {name:'Scary Face',    type:'normal',  cat:'status',   power:null,acc:100, pp:10,
                  effect:'deboss', stat:'spe', stages:-2},
  charm:        {name:'Charm',         type:'fairy',   cat:'status',   power:null,acc:100, pp:20,
                  effect:'debuff', stat:'atk', stages:-2},
  smokescreen:  {name:'Smokescreen',   type:'normal',  cat:'status',   power:null,acc:100, pp:20,
                  effect:'debuff', stat:'acc', stages:-1},
  swords_dance: {name:'Swords Dance',  type:'normal',  cat:'status',   power:null,acc:null, pp:20,
                  effect:'buff', stat:'atk', stages:2},
  harden:       {name:'Harden',        type:'normal',  cat:'status',   power:null,acc:null, pp:30,
                  effect:'buff', stat:'def', stages:1},
  defense_curl: {name:'Defense Curl',  type:'normal',  cat:'status',   power:null,acc:null, pp:40,
                  effect:'buff', stat:'def', stages:1},
  belly_drum:   {name:'Belly Drum',    type:'normal',  cat:'status',   power:null,acc:null, pp:10,
                  effect:'buff', stat:'atk', stages:6},
  work_up:      {name:'Work Up',       type:'normal',  cat:'status',   power:null,acc:null, pp:30,
                  effect:'buff', stat:'atk', stages:1},
  recover:      {name:'Recover',       type:'normal',  cat:'status',   power:null,acc:null, pp:10,
                  effect:'heal'},
  safeguard:    {name:'Safeguard',     type:'normal',  cat:'status',   power:null,acc:null, pp:25},
  supersonic:   {name:'Supersonic',    type:'normal',  cat:'status',   power:null,acc:55,  pp:20,
                  effect:'confusion'},
  focus_energy: {name:'Focus Energy',  type:'normal',  cat:'status',   power:null,acc:null, pp:30,
                  effect:'buff', stat:'crit', stages:2},    // +2 estágios de critical ratio
  encore:       {name:'Encore',        type:'normal',  cat:'status',   power:null,acc:100, pp:5},
  odor_sleuth:  {name:'Odor Sleuth',   type:'normal',  cat:'status',   power:null,acc:null, pp:40},
  // ► ROAR — adaptado: duplo buff DEF + Sp.DEF +1 em um turno
  roar:         {name:'Roar',          type:'normal',  cat:'status',   power:null,acc:null, pp:20,
                  effect:'double_buff', stat:['def','spd'], stages:1},
  // ── Water ───────────────────────────────────────────────────
  water_gun:    {name:'Water Gun',     type:'water',   cat:'special',  power:40,  acc:100, pp:25},
  bubble:       {name:'Bubble',        type:'water',   cat:'special',  power:40,  acc:100, pp:30},
  surf:         {name:'Surf',          type:'water',   cat:'special',  power:90,  acc:100, pp:15},
  hydro_pump:   {name:'Hydro Pump',    type:'water',   cat:'special',  power:110, acc:80,  pp:5},
  scald:        {name:'Scald',         type:'water',   cat:'special',  power:80,  acc:100, pp:15},
  water_pulse:  {name:'Water Pulse',   type:'water',   cat:'special',  power:60,  acc:100, pp:20},
  aqua_tail:    {name:'Aqua Tail',     type:'water',   cat:'physical', power:90,  acc:90,  pp:10},
  aqua_jet:     {name:'Aqua Jet',      type:'water',   cat:'physical', power:40,  acc:100, pp:20},
  razor_shell:  {name:'Razor Shell',   type:'water',   cat:'physical', power:75,  acc:95,  pp:10},
  rain_dance:   {name:'Rain Dance',    type:'water',   cat:'status',   power:null,acc:null, pp:5},
  withdraw:     {name:'Withdraw',      type:'water',   cat:'status',   power:null,acc:null, pp:40,
                  effect:'buff', stat:'def', stages:1},
  // ── Fire ────────────────────────────────────────────────────
  ember:        {name:'Ember',         type:'fire',    cat:'special',  power:40,  acc:100, pp:25,
                  effect:'burn', effectChance:10},
  flamethrower: {name:'Flamethrower',  type:'fire',    cat:'special',  power:90,  acc:100, pp:15},
  fire_blast:   {name:'Fire Blast',    type:'fire',    cat:'special',  power:110, acc:85,  pp:5},
  overheat:     {name:'Overheat',      type:'fire',    cat:'special',  power:130, acc:90,  pp:5},
  flare_blitz:  {name:'Flare Blitz',   type:'fire',    cat:'physical', power:120, acc:100, pp:15},
  flame_charge: {name:'Flame Charge',  type:'fire',    cat:'physical', power:50,  acc:100, pp:20},
  fire_fang:    {name:'Fire Fang',     type:'fire',    cat:'physical', power:65,  acc:95,  pp:15,
                  effect:'burn', effectChance:10},
  fire_spin:    {name:'Fire Spin',     type:'fire',    cat:'special',  power:35,  acc:85,  pp:15},
  heat_crash:   {name:'Heat Crash',    type:'fire',    cat:'physical', power:null,acc:100, pp:10},
  heat_wave:    {name:'Heat Wave',     type:'fire',    cat:'special',  power:95,  acc:90,  pp:10},
  inferno:      {name:'Inferno',       type:'fire',    cat:'special',  power:100, acc:50,  pp:5,
                  effect:'burn', effectChance:100},
  will_o_wisp:  {name:'Will-O-Wisp',   type:'fire',    cat:'status',   power:null,acc:85,  pp:15,
                  effect:'burn'},
  // ── Grass ───────────────────────────────────────────────────
  vine_whip:    {name:'Vine Whip',     type:'grass',   cat:'physical', power:45,  acc:100, pp:25},
  branch_poke:  {name:'Branch Poke',   type:'grass',   cat:'physical', power:40,  acc:100, pp:40},
  razor_leaf:   {name:'Razor Leaf',    type:'grass',   cat:'physical', power:55,  acc:95,  pp:25},
  seed_bomb:    {name:'Seed Bomb',     type:'grass',   cat:'physical', power:80,  acc:100, pp:15},
  leaf_blade:   {name:'Leaf Blade',    type:'grass',   cat:'physical', power:90,  acc:100, pp:15},
  wood_hammer:  {name:'Wood Hammer',   type:'grass',   cat:'physical', power:120, acc:100, pp:15},
  magical_leaf: {name:'Magical Leaf',  type:'grass',   cat:'special',  power:60,  acc:null, pp:20},
  // ► LEAFAGE — físico, 40 PWR, sem efeito
  leafage:      {name:'Leafage',       type:'grass',   cat:'physical', power:40,  acc:100, pp:40},
  absorb:       {name:'Absorb',        type:'grass',   cat:'special',  power:20,  acc:100, pp:25},
  mega_drain:   {name:'Mega Drain',    type:'grass',   cat:'special',  power:40,  acc:100, pp:15},
  giga_drain:   {name:'Giga Drain',    type:'grass',   cat:'special',  power:75,  acc:100, pp:10},
  energy_ball:  {name:'Energy Ball',   type:'grass',   cat:'special',  power:90,  acc:100, pp:10},
  leaf_storm:   {name:'Leaf Storm',    type:'grass',   cat:'special',  power:130, acc:90,  pp:5},
  petal_blizzard:{name:'Petal Blizzard',type:'grass',  cat:'physical', power:90,  acc:100, pp:15},
  // ► LEECH SEED — planta semente; drena 1/8 HP/turno; imune: grass-types
  leech_seed:   {name:'Leech Seed',    type:'grass',   cat:'status',   power:null,acc:90,  pp:10,
                  effect:'leech_seed'},
  sleep_powder: {name:'Sleep Powder',  type:'grass',   cat:'status',   power:null,acc:75,  pp:15,
                  effect:'sleep'},
  stun_spore:   {name:'Stun Spore',    type:'grass',   cat:'status',   power:null,acc:75,  pp:30,
                  effect:'paralysis'},
  cotton_guard: {name:'Cotton Guard',  type:'grass',   cat:'status',   power:null,acc:null, pp:10,
                  effect:'buff', stat:'def', stages:3},
  synthesis:    {name:'Synthesis',     type:'grass',   cat:'status',   power:null,acc:null, pp:5},
  sweet_scent:  {name:'Sweet Scent',   type:'normal',  cat:'status',   power:null,acc:100, pp:20,
                  effect:'debuff', stat:'acc', stages:-1},
  growth:       {name:'Growth',        type:'normal',  cat:'status',   power:null,acc:null, pp:20,
                  effect:'buff', stat:'spa', stages:1},
  coil:         {name:'Coil',          type:'poison',  cat:'status',   power:null,acc:null, pp:20,
                  effect:'buff', stat:'atk', stages:1},
  leaf_tornado: {name:'Leaf Tornado',  type:'grass',   cat:'special',  power:65,  acc:90,  pp:10,
                  effect:'debuff', stat:'acc', stages:-1, effectChance:50},
  // ── Electric ────────────────────────────────────────────────
  thundershock: {name:'ThunderShock',  type:'electric',cat:'special',  power:40,  acc:100, pp:30},
  thunderbolt:  {name:'Thunderbolt',   type:'electric',cat:'special',  power:90,  acc:100, pp:15},
  thunder:      {name:'Thunder',       type:'electric',cat:'special',  power:110, acc:70,  pp:10},
  // ── Psychic ─────────────────────────────────────────────────
  psychic_move: {name:'Psychic',       type:'psychic', cat:'special',  power:90,  acc:100, pp:10},
  psybeam:      {name:'Psybeam',       type:'psychic', cat:'special',  power:65,  acc:100, pp:20},
  psyshock:     {name:'Psyshock',      type:'psychic', cat:'special',  power:80,  acc:100, pp:10},
  hypnosis:     {name:'Hypnosis',      type:'psychic', cat:'status',   power:null,acc:60,  pp:20,
                  effect:'sleep'},
  calm_mind:    {name:'Calm Mind',     type:'psychic', cat:'status',   power:null,acc:null, pp:20,
                  effect:'buff', stat:'spa', stages:1},
  agility:      {name:'Agility',       type:'psychic', cat:'status',   power:null,acc:null, pp:30,
                  effect:'buff', stat:'spe', stages:2},
  amnesia:      {name:'Amnesia',       type:'psychic', cat:'status',   power:null,acc:null, pp:20,
                  effect:'buff', stat:'spd', stages:2},
  light_screen: {name:'Light Screen',  type:'psychic', cat:'status',   power:null,acc:null, pp:30},
  // ── Ground ──────────────────────────────────────────────────
  earthquake:   {name:'Earthquake',    type:'ground',  cat:'physical', power:100, acc:100, pp:10},
  mud_slap:     {name:'Mud-Slap',      type:'ground',  cat:'special',  power:20,  acc:100, pp:10,
                  effect:'debuff', stat:'acc', stages:-1, effectChance:100},
  bulldoze:     {name:'Bulldoze',      type:'ground',  cat:'physical', power:60,  acc:100, pp:20,
                  effect:'debuff', stat:'spe', stages:-1, effectChance:100},
  sand_attack:  {name:'Sand Attack',   type:'ground',  cat:'status',   power:null,acc:100, pp:15,
                  effect:'debuff', stat:'acc', stages:-1},
  stomping_tantrum:{name:'Stomping Tantrum',type:'ground',cat:'physical',power:75, acc:100, pp:10},
  // ── Ghost ───────────────────────────────────────────────────
  shadow_sneak: {name:'Shadow Sneak',  type:'ghost',   cat:'physical', power:40,  acc:100, pp:30},
  shadow_ball:  {name:'Shadow Ball',   type:'ghost',   cat:'special',  power:80,  acc:100, pp:15},
  hex:          {name:'Hex',           type:'ghost',   cat:'special',  power:65,  acc:100, pp:10},
  lick:         {name:'Lick',          type:'ghost',   cat:'physical', power:30,  acc:100, pp:30,
                  effect:'paralysis', effectChance:30},
  astonish:     {name:'Astonish',      type:'ghost',   cat:'physical', power:30,  acc:100, pp:15},
  confuse_ray:  {name:'Confuse Ray',   type:'ghost',   cat:'status',   power:null,acc:100, pp:10,
                  effect:'confusion'},
  // ── Dark ────────────────────────────────────────────────────
  crunch:       {name:'Crunch',        type:'dark',    cat:'physical', power:80,  acc:100, pp:15},
  knock_off:    {name:'Knock Off',     type:'dark',    cat:'physical', power:65,  acc:100, pp:20},
  sucker_punch: {name:'Sucker Punch',  type:'dark',    cat:'physical', power:70,  acc:100, pp:5},
  bite:         {name:'Bite',          type:'dark',    cat:'physical', power:60,  acc:100, pp:25},
  nasty_plot:   {name:'Nasty Plot',    type:'dark',    cat:'status',   power:null,acc:null, pp:20,
                  effect:'buff', stat:'spa', stages:2},
  fake_tears:   {name:'Fake Tears',    type:'dark',    cat:'status',   power:null,acc:100, pp:20,
                  effect:'debuff', stat:'spd', stages:-2},
  taunt:        {name:'Taunt',         type:'dark',    cat:'status',   power:null,acc:100, pp:20},
  torment:      {name:'Torment',       type:'dark',    cat:'status',   power:null,acc:100, pp:15},
  swagger:      {name:'Swagger',       type:'normal',  cat:'status',   power:null,acc:85,  pp:15,
                  effect:'confusion'},
  roar:         {name:'Roar',          type:'normal',  cat:'status',   power:null,acc:null, pp:20,
                  effect:'double_buff', stat:['def','spd'], stages:1},
  // ── Dragon ──────────────────────────────────────────────────
  dragon_pulse: {name:'Dragon Pulse',  type:'dragon',  cat:'special',  power:85,  acc:100, pp:10},
  dragon_breath:{name:'DragonBreath',  type:'dragon',  cat:'special',  power:60,  acc:100, pp:20},
  outrage:      {name:'Outrage',       type:'dragon',  cat:'physical', power:120, acc:100, pp:10},
  // ── Flying ──────────────────────────────────────────────────
  aerial_ace:   {name:'Aerial Ace',    type:'flying',  cat:'physical', power:60,  acc:null, pp:20},
  brave_bird:   {name:'Brave Bird',    type:'flying',  cat:'physical', power:120, acc:100, pp:15},
  wing_attack:  {name:'Wing Attack',   type:'flying',  cat:'physical', power:60,  acc:100, pp:35},
  gust:         {name:'Gust',          type:'flying',  cat:'special',  power:40,  acc:100, pp:35},
  bounce:       {name:'Bounce',        type:'flying',  cat:'physical', power:85,  acc:85,  pp:5},
  peck:         {name:'Peck',          type:'flying',  cat:'physical', power:35,  acc:100, pp:35},
  tailwind:     {name:'Tailwind',      type:'flying',  cat:'status',   power:null,acc:null, pp:15,
                  effect:'buff', stat:'spe', stages:2},
  mirror_move:  {name:'Mirror Move',   type:'flying',  cat:'status',   power:null,acc:null, pp:20},
  // ── Bug ─────────────────────────────────────────────────────
  bug_bite:     {name:'Bug Bite',      type:'bug',     cat:'physical', power:60,  acc:100, pp:20},
  bug_buzz:     {name:'Bug Buzz',      type:'bug',     cat:'special',  power:90,  acc:100, pp:10,
                  effect:'debuff', stat:'spd', stages:-1, effectChance:10},
  silver_wind:  {name:'Silver Wind',   type:'bug',     cat:'special',  power:60,  acc:100, pp:5},
  fury_cutter:  {name:'Fury Cutter',   type:'bug',     cat:'physical', power:40,  acc:95,  pp:20},
  pin_missile:  {name:'Pin Missile',   type:'bug',     cat:'physical', power:25,  acc:95,  pp:20},
  x_scissor:    {name:'X-Scissor',     type:'bug',     cat:'physical', power:80,  acc:100, pp:15},
  lunge:        {name:'Lunge',         type:'bug',     cat:'physical', power:80,  acc:100, pp:15,
                  effect:'debuff', stat:'atk', stages:-1, effectChance:100},
  string_shot:  {name:'String Shot',   type:'bug',     cat:'status',   power:null,acc:95,  pp:40,
                  effect:'debuff', stat:'spe', stages:-2},
  // ── Poison ──────────────────────────────────────────────────
  poison_sting: {name:'Poison Sting',  type:'poison',  cat:'physical', power:15,  acc:100, pp:35,
                  effect:'poison', effectChance:30},
  twineedle:    {name:'Twineedle',     type:'bug',     cat:'physical', power:25,  acc:100, pp:20,
                  effect:'poison', effectChance:20},
  poison_jab:   {name:'Poison Jab',    type:'poison',  cat:'physical', power:80,  acc:100, pp:20,
                  effect:'poison', effectChance:30},
  poison_powder:{name:'Poison Powder', type:'poison',  cat:'status',   power:null,acc:75,  pp:35,
                  effect:'poison'},
  // ► TOXIC SPIKES — envenena imediatamente todos os alvos (exceto poison-type)
  toxic_spikes: {name:'Toxic Spikes',  type:'poison',  cat:'status',   power:null,acc:null,pp:20,
                  effect:'toxic_spikes'},
  smog:         {name:'Smog',          type:'poison',  cat:'special',  power:30,  acc:70,  pp:20},
  toxic:        {name:'Toxic',         type:'poison',  cat:'status',   power:null,acc:90,  pp:10,
                  effect:'toxic'},
  acid_armor:   {name:'Acid Armor',    type:'poison',  cat:'status',   power:null,acc:null, pp:20,
                  effect:'buff', stat:'def', stages:2},
  // ── Rock ────────────────────────────────────────────────────
  stone_edge:   {name:'Stone Edge',    type:'rock',    cat:'physical', power:100, acc:80,  pp:5},
  rock_blast:   {name:'Rock Blast',    type:'rock',    cat:'physical', power:25,  acc:90,  pp:10},
  rollout:      {name:'Rollout',       type:'rock',    cat:'physical', power:30,  acc:90,  pp:20},
  // ── Steel ───────────────────────────────────────────────────
  iron_head:    {name:'Iron Head',     type:'steel',   cat:'physical', power:80,  acc:100, pp:15},
  iron_defense: {name:'Iron Defense',  type:'steel',   cat:'status',   power:null,acc:null, pp:15,
                  effect:'buff', stat:'def', stages:2},
  // ── Ice ─────────────────────────────────────────────────────
  blizzard:     {name:'Blizzard',      type:'ice',     cat:'special',  power:110, acc:70,  pp:5},
  ice_beam:     {name:'Ice Beam',      type:'ice',     cat:'special',  power:90,  acc:100, pp:10},
  ice_fang:     {name:'Ice Fang',      type:'ice',     cat:'physical', power:65,  acc:95,  pp:15},
  // ── Fairy ───────────────────────────────────────────────────
  play_rough:   {name:'Play Rough',    type:'fairy',   cat:'physical', power:90,  acc:90,  pp:10},
  moonblast:    {name:'Moonblast',     type:'fairy',   cat:'special',  power:95,  acc:100, pp:15},
  // ── Fighting ────────────────────────────────────────────────
  close_combat: {name:'Close Combat',  type:'fighting',cat:'physical', power:120, acc:100, pp:5},
  aura_sphere:  {name:'Aura Sphere',   type:'fighting',cat:'special',  power:80,  acc:null, pp:20},
  double_kick:  {name:'Double Kick',   type:'fighting',cat:'physical', power:30,  acc:100, pp:30},
  bulk_up:      {name:'Bulk Up',       type:'fighting',cat:'status',   power:null,acc:null, pp:20,
                  effect:'buff', stat:'atk', stages:1},
  high_jump_kick:{name:'High Jump Kick',type:'fighting',cat:'physical',power:130, acc:90,  pp:10},
  mach_punch:   {name:'Mach Punch',    type:'fighting',cat:'physical', power:40,  acc:100, pp:30,
                  priority:1},
  revenge:      {name:'Revenge',       type:'fighting',cat:'physical', power:60,  acc:100, pp:10},
  // ── Dark extra ──────────────────────────────────────────────
  // ► BRUTAL SWING — dark, physical, 60 PWR, sem efeito
  brutal_swing: {name:'Brutal Swing',  type:'dark',    cat:'physical', power:60,  acc:100, pp:20},
  // ── Ground extra ────────────────────────────────────────────
  // ► DRILL RUN — ground, physical, 80 PWR, 95 ACC; crit 1/8 (highCrit:true)
  drill_run:    {name:'Drill Run',     type:'ground',  cat:'physical', power:80,  acc:95,  pp:10,
                  highCrit:true},
  stone_edge:   {name:'Stone Edge',    type:'rock',    cat:'physical', power:100, acc:80,  pp:5},
  rock_blast:   {name:'Rock Blast',    type:'rock',    cat:'physical', power:25,  acc:90,  pp:10},
  rollout:      {name:'Rollout',       type:'rock',    cat:'physical', power:30,  acc:90,  pp:20},
  // ── Steel ───────────────────────────────────────────────────
  iron_head:    {name:'Iron Head',     type:'steel',   cat:'physical', power:80,  acc:100, pp:15},
  iron_defense: {name:'Iron Defense',  type:'steel',   cat:'status',   power:null,acc:null, pp:15,
                  effect:'buff', stat:'def', stages:2},
  // ── Ice ─────────────────────────────────────────────────────
  blizzard:     {name:'Blizzard',      type:'ice',     cat:'special',  power:110, acc:70,  pp:5},
  ice_beam:     {name:'Ice Beam',      type:'ice',     cat:'special',  power:90,  acc:100, pp:10},
  ice_fang:     {name:'Ice Fang',      type:'ice',     cat:'physical', power:65,  acc:95,  pp:15},
  // ── Fairy ───────────────────────────────────────────────────
  play_rough:   {name:'Play Rough',    type:'fairy',   cat:'physical', power:90,  acc:90,  pp:10},
  moonblast:    {name:'Moonblast',     type:'fairy',   cat:'special',  power:95,  acc:100, pp:15},
  // ── Fighting ────────────────────────────────────────────────
  close_combat: {name:'Close Combat',  type:'fighting',cat:'physical', power:120, acc:100, pp:5},
  aura_sphere:  {name:'Aura Sphere',   type:'fighting',cat:'special',  power:80,  acc:null, pp:20},
  double_kick:  {name:'Double Kick',   type:'fighting',cat:'physical', power:30,  acc:100, pp:30},
  bulk_up:      {name:'Bulk Up',       type:'fighting',cat:'status',   power:null,acc:null, pp:20,
                  effect:'buff', stat:'atk', stages:1},
  high_jump_kick:{name:'High Jump Kick',type:'fighting',cat:'physical',power:130, acc:90,  pp:10},
  mach_punch:   {name:'Mach Punch',    type:'fighting',cat:'physical', power:40,  acc:100, pp:30,
                  priority:1},
  revenge:      {name:'Revenge',       type:'fighting',cat:'physical', power:60,  acc:100, pp:10},
  // ── Misc ────────────────────────────────────────────────────
  pyro_ball:    {name:'Pyro Ball',     type:'fire',    cat:'physical', power:120, acc:90,  pp:5,
                  effect:'burn', effectChance:10},
  wrap:         {name:'Wrap',          type:'normal',  cat:'physical', power:15,  acc:90,  pp:20},
  facade:       {name:'Facade',        type:'normal',  cat:'physical', power:70,  acc:100, pp:20},
  slack_off:    {name:'Slack Off',     type:'normal',  cat:'status',   power:null,acc:null, pp:10,
                  effect:'heal'},
  wring_out:    {name:'Wring Out',     type:'normal',  cat:'special',  power:null,acc:100, pp:5},
  flail:        {name:'Flail',         type:'normal',  cat:'physical', power:null,acc:100, pp:15},
  chip_away:    {name:'Chip Away',     type:'normal',  cat:'physical', power:70,  acc:100, pp:20},
  super_power:  {name:'Super Power',   type:'fighting',cat:'physical', power:120, acc:100, pp:5},
  rage:         {name:'Rage',          type:'normal',  cat:'physical', power:20,  acc:100, pp:20},
  smokescreen:  {name:'Smokescreen',   type:'normal',  cat:'status',   power:null,acc:100, pp:20,
                  effect:'debuff', stat:'acc', stages:-1},
  psybeam:      {name:'Psybeam',       type:'psychic', cat:'special',  power:65,  acc:100, pp:20},
  lucky_chant:  {name:'Lucky Chant',   type:'normal',  cat:'status',   power:null,acc:null, pp:30},
  water_sport:  {name:'Water Sport',   type:'water',   cat:'status',   power:null,acc:null, pp:15},
  foresight:    {name:'Foresight',     type:'normal',  cat:'status',   power:null,acc:null, pp:40},
  protect:      {name:'Protect',       type:'normal',  cat:'status',   power:null,acc:null, pp:10},
  mud_shot:     {name:'Mud Shot',      type:'ground',  cat:'special',  power:55,  acc:95,  pp:15,
                  effect:'debuff', stat:'spe', stages:-1, effectChance:100},
  bide:         {name:'Bide',          type:'normal',  cat:'physical', power:null,acc:null, pp:10},
  quiver_dance: {name:'Quiver Dance',  type:'bug',     cat:'status',   power:null,acc:null, pp:20,
                  effect:'buff', stat:'spa', stages:1},
  // ── Explosion — bloqueados por Damp ─────────────────────────
  explosion:    {name:'Explosion',     type:'normal',  cat:'physical', power:250, acc:100, pp:5,
                  effect:'explosion'},
  self_destruct:{name:'Self-Destruct', type:'normal',  cat:'physical', power:200, acc:100, pp:5,
                  effect:'explosion'},
};
